### PR TITLE
Add new alt names for DESI / WGS

### PR DESCRIPTION
**Pull request by NickAkhmetov**
Related to slack conversation: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1686765942747269?thread_ts=1686750725.282249&cid=C011RF3NQ23

### CODE REVIEW

**Comment by NickAkhmetov** [comment]
> Is this PR to address some of the issues I posted from the reindex errors?
Yes, since these appeared to be close lexical matches for existing terms with either initializations or the use of dashes vs. spaces, I assumed that these could be included as synonyms; there are a few other existing cases in the assays yaml file where this is already the case. If this assumption is incorrect, I'm happy to drop this PR 😄 

> I remember you mentioned some portal transformation logic problems, have you come up with a solution?
We discovered the source of the regression with metadata tables and have fixed it on the front-end. 

> any other issues regarding the deprecated fields?
We did not find any further data-related issues during QA testing on Friday, and will perform another round of QA testing for 0.73.0.

**Comment by lchoy** [comment]
> @lchoy I remember you mentioned some portal transformation logic problems, have you come up with a solution?

We still need to perform the cleanup for the portal transformation logic, but the issues we were seeing were actually related to other changes. These have been addressed in portal-ui 0.73.0.

**Comment by NickAkhmetov** [comment]
From my perspective, since the yaml file is in use right now, it makes sense to keep it up to date until the indexing process is updated to use the UBKG ontology and these changes were made to dismiss the indexing errors you had observed. With that said, it's fully up to your discretion if you'd prefer to take that path forward; no feelings will be hurt if this PR is closed instead 😄

**Comment by AlanSimmons** [comment]
I will update the source for the ontology neo4j instance today to add alt names for the DESI and WGS assay types.

**Comment by NickAkhmetov** [comment]
I opened another PR against this branch (#689) to cover the changes to `vitessce-hints` for `mibi deepcell` assays/avoid conflicts.

**Comment by yuanzhou** [comment]
@NickAkhmetov let's move forward with this PR for now. I'll get it merged and redeployed on DEV.

**Comment by AlanSimmons** [comment]
By the way, the ontology neo4j that either was already deployed to production or will be very soon should reflect these changes.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
