### PR TITLE
Update assay_types.yml to include DESI

### PR DESCRIPTION
**Pull request by bhonick**
Added DESI + image pyramid variant

### CODE REVIEW

**Comment by yuanzhou** [comment]
@bhonick our workflow is get things tested on the DEV environment first via a PR from a new branch into `dev-integrate` before we send a PR from your same branch to the `main` for TEST and PROD environments. Do you mind if I change the base branch of this PR to `dev-integrate`?

**Comment by bhonick** [comment]
@yuanzhou Whoops, sorry! Sure, that would be great, thank you!

**Comment by yuanzhou** [comment]
Thanks @bhonick, also just so you know there are other previous PRs in the queue, we normally test one thing at a time then move on to the next one. I'll let you know when yours is ready for merge and redeployment after all the reviewers have approved this PR, if it doesn't happen in a day or two.

**Comment by bhonick** [comment]
@yuanzhou Thanks for the insight! I'm noting this information for future issues.

**Comment by yuanzhou** [comment]
Adding @AlanSimmons as one of the reviewers per Bill's suggestion.

**Comment by AlanSimmons** [comment]
@bhonick It has been my experience that the *_pyramid assay types are deprecated, even though they are still in the assay_types.yaml. This is the case for AF_pyramid, IMC2D_pyramid, etc. I can see no entities for datasets with these values of data_type.  The only data_type that is still relevant is image_pyramid.

Do you really need the DESI_pyramid assay/data type?

**Comment by AlanSimmons** [comment]
The change looks okay to me. I will transfer information on the DESI assay type to the HuBMAP application ontology for the next release of the ontology.

**Review by AlanSimmons — APPROVED** [review]

**Comment by bhonick** [comment]
@AlanSimmons Thanks for looking this over. I merely added the DESI_pyramid since I did not know about the deprecation. Shall I remove that part of the YAML?

**Comment by AlanSimmons** [comment]
@bhonick You can leave the change as is. I'll ignore DESI_pyramid with respect to the ontology. Once the ontology is the source of truth and we replace calls that read assay_types.yaml with calls to the ontology api,  the assay_types.yaml file will no longer be relevant.

FYI @shirey

**Comment by bhonick** [comment]
@AlanSimmons Thanks! Sounds good to me. 

@yuanzhou It sounds like this is now ready for testing whenever it comes up in your queue, thanks!

**Comment by yuanzhou** [comment]
@sunset666 can you take a look and approve if good? Then I'll get it merged and redeployed on DEV for testing.

**Review by sunset666 — APPROVED** [review]

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
