### PR TITLE
Mccalluc/partonomy index error

### LINKED ISSUE #244: Reindex error
I did a reindex on TEST with the latest PROD neo4j copy using the `test-release` branch, which uses the refactored entity-api and refactored indexer. At the time the reindex was executed, the `test-release` branch had already merged the PR #242 

Example error:
````
[2021-03-06 19:38:04] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 4e8d64722e354aa4c14def7009440c19
Traceback (most recent call last):
  File "/usr/src/app/src/elasticsearch/indexer.py", line 508, in update_index
    transformed = json.dumps(transform(json.loads(doc)))
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/__init__.py", line 145, in transform
    add_partonomy(doc_copy)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/add_partonomy.py", line 30, in add_partonomy
    ancestor_list = _get_ancestors_of(uri, index)
  File "/usr/src/app/src/elasticsearch/addl_index_transformations/portal/add_partonomy.py", line 36, in _get_ancestors_of
    node = index[node_id]
KeyError: 'http://purl.org/sig/ont/fma/fma15828'
````

And a list of uuids that threw this error:
````
[2021-03-06 19:03:19] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 3d2bc79885fc7720f77fddd2c23f02e5
[2021-03-06 19:04:06] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 5f043da4d6347e2b6f93509c000804d1
[2021-03-06 19:04:34] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: d093d6563dad2457356074c3781d9bea
[2021-03-06 19:05:07] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 17cdad1671514b52baaeee599fa06ebf
[2021-03-06 19:05:11] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 39c3c7a6fb9f98c346065eb771febd08
[2021-03-06 19:09:33] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 074c96e0c614d3f8132a60afdd536db4
[2021-03-06 19:09:47] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 960f1766a95573bb5ccd5e45c81a7e1b
[2021-03-06 19:11:07] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 988d21f5795b193ba51a7e00b1574ddf
[2021-03-06 19:11:34] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: f50b8ce55392beae9fa0547a81288f25
[2021-03-06 19:14:03] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 4fb887c5b17d203e20143d9044c0bf94
[2021-03-06 19:14:59] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 8d593ea6872956bb98ced0e9b8fda5c8
[2021-03-06 19:15:24] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: ef2f2dc788ae3e63ed9649d69c3ec7f5
[2021-03-06 19:15:57] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 7000456f479ecdd3a5c7f4ba70ada709
[2021-03-06 19:36:01] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 01b0f11f3fc13542c6d837cc47712b85
[2021-03-06 19:36:11] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: ba906793fcba084898ac24e850d5a964
[2021-03-06 19:36:15] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 798978f4efbbbe2d061651bd1460a9c3
[2021-03-06 19:36:23] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 3f431785d52ce16e00102749e5eca384
[2021-03-06 19:36:27] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 84089f9d892b2a3f580d078ce2423656
[2021-03-06 19:36:48] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 191050c2ef9bb9314d0057b48e31ab0d
[2021-03-06 19:36:51] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 7c504503496b18f731a95e844884f591
[2021-03-06 19:37:01] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 2aefc156eeab64b7ca8efc49425f39c0
[2021-03-06 19:37:04] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: f3f064df9fba093884256bf9f99aacaa
[2021-03-06 19:37:12] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 379708792c96e7679337c17651551950
[2021-03-06 19:37:19] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 32e38bed28499ae00c3b2c45831bc9b4
[2021-03-06 19:37:36] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: eb580ab691158f63336056cbb9920f5b
[2021-03-06 19:37:40] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 5a743beb0514fc5c6d80c58342c645d9
[2021-03-06 19:37:47] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: e639a1b529940388a533ef0124c69ac9
[2021-03-06 19:37:57] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 51cb57b4d8dd205b9c60a9f1daf599f8
[2021-03-06 19:38:04] ERROR in indexer: Exception encountered during executing indexer.update_index() for uuid: 4e8d64722e354aa4c14def7009440c19
````

@mccalluc any insights?

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #244

### CODE REVIEW

**Comment by mccalluc** [comment]
@yuanzhou - It looks like tests have been broken on this branch for several commits. That shouldn't have happened, but this fixes it.

**Comment by yuanzhou** [comment]
@mccalluc thanks for quick fix! Regarding the failed CI test, couple things to clarify:
- the `src/requirements.txt` is the one should be used by CI build, because it installs the specified commons branch via `COMMONS_BRANCH` (https://github.com/hubmapconsortium/search-api/blob/test-release/src/requirements.txt#L9) 
- the `src/requirements_dev.txt` is only used by developers who want to experiment locally using the local version of commons (many cases are they make changes in commons too, so use a local version instead of installing the github branch). That's why I removed this from the CI: https://github.com/hubmapconsortium/search-api/commit/c4a96ed33dde8984f104feb62c68a403d1a0bae9#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485

Two things to consider and discuss:
- Should we use `test-release` branch of commons instead of the master branch in CI? https://github.com/hubmapconsortium/search-api/blob/test-release/.travis.yml#L6 considering the `test-release` is the default branch now, and the master branch is the released version that may not contain new features and bug fixes needed for the build.
- We may want to create a new CI dependency install file, `requirements_ci.txt` and put flake8 and other dependencies only used by CI tests, and add to the `install` section in addition to the `requirements.txt` install: https://github.com/hubmapconsortium/search-api/blob/test-release/.travis.yml#L8

**Comment by mccalluc** [comment]
> Should we use test-release branch of commons instead of the master branch in CI?

I would vote for neither of the above: I believe dependencies should be pinned to explicit version numbers. (Dependencies in libraries are different: they need to specify the range they can work with.) If tests pass in a particular repo at a particular version, they should continue to pass, and not start failing because HEAD on a different repo introduced a breaking change.

This would obviate #238 entirely: It would just work like any other dependency.

> We may want to create a new CI dependency install file

Typically, dev or ci dependencies are specified _in addition_ to the base `requires.txt`: right now, `requires.txt` is copied over, with the (weird) `commons` dependency tweaked. Besides being a non-standard practice, it means that these may drift out of sync over time, because developers see one version of a dependency, but it's being deployed or tested with another version.

Let's not continue this discussion in this PR.

**Comment by yuanzhou** [comment]
@mccalluc My bad, I just realized the old `requirements-dev.txt` is different from the `requirements_dev.txt` used in other repos. Fixed that in the `test-release` branch and appended the fixes to this PR. Sorry about not paying too much attention to the differences.

**Pull request merged**
