### PR TITLE
Use new JSON-LD for anatomy

### PR DESCRIPTION
**Pull request by mccalluc**
### Fix test failures

@yuanzhou / @shirey : I think this should address tests that have been failing since [Bill's commit last week](https://github.com/hubmapconsortium/search-api/commit/762f5aee70b7d59b98194617a57ec67440b80d49) that removed `LY01` etc., but I'm not sure, since CI still isn't running.

I think we're on the same page that moving forward, tests need to be passing before merging to `test-release`? In particular, this means that not even configuration changes should be made directly to `test-release` without PR: Even a configuration change can cause tests to fail. I also think that we're on that same page that it is the responsibility of the Pittsburgh team to keep the CI itself running, whichever service you want to use.

### Upgrade partonomy

@bherr2 : This upgrades the partonomy: It looks like there is good stuff in there, but I think there are still problems. The [top level of the tree](https://github.com/hubmapconsortium/search-api/pull/378/files#diff-55826f44f8623673cb436d1272f9e5a399197923412f52d750465f5d13b87888R76-R81) seems weird:
```
     ...
     'retromandibular vein',
     'skin',
     'spleen',
     'spleen',
     'spleen',
     'telencephalic ventricle',
     ....
```
- Why is `spleen` repeated?
- What's up with `retromandibular vein` and `telencephalic ventricle`? These don't seem like they belong at the top level.

Going forward, as there are new partonomy releases, I think it would make sense for Bruce to start PRs in this repo, and just loop me in as a reviewer if needed.

### CODE REVIEW

**Review by bherr2 — APPROVED** [review]

**Review by shirey — APPROVED** [review]
Thanks for fixing.

**Comment by yuanzhou** [comment]
Thanks @mccalluc. And we are on the same page:
>I think we're on the same page that moving forward, tests need to be passing before merging to test-release? In particular, this means that not even configuration changes should be made directly to test-release without PR: Even a configuration change can cause tests to fail. I also think that we're on that same page that it is the responsibility of the Pittsburgh team to keep the CI itself running, whichever service you want to use.

I've tested the Travis CI after the payment issue addressed, also updated Github settings of this repo to require status checks to pass before merging.

**Comment by mccalluc** [comment]
@yuanzhou -- great; In this repo, you'll do the merge? Thanks!

**Review by yuanzhou — APPROVED** [review]

**Comment by yuanzhou** [comment]
@mccalluc yes, I'll take care of the merge and deployment.

**Pull request merged**
