### PR TITLE
(chore): bump `portal-visualization` to 0.0.12

### PR DESCRIPTION
**Pull request by ilan-gold**
Brings in https://github.com/hubmapconsortium/portal-visualization/pull/79

### CODE REVIEW

**Comment by ilan-gold** [comment]
@NickAkhmetov Not sure how to coordinate these but figured you would know because you did it recently

**Comment by NickAkhmetov** [comment]
@ilan-gold To my knowledge, we should be good to merge this and the corresponding change in portal UI in any order as long as we deploy them at the same time

**Comment by ilan-gold** [comment]
Ok @NickAkhmetov (or @yuanzhou), just need a review here then!  Please advise on how to coordinate the release as well!

**Comment by yuanzhou** [comment]
@ilan-gold @NickAkhmetov let's get this out on DEV to find out.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
