### PR TITLE
Welling/unified assay names 202011

### PR DESCRIPTION
**Pull request by jswelling**
This update introduces lib/assay_types.py with class AssayTypes, and adds REST entry points to provide assay type info to search-api.  Assay types gain a 'primary' attribute for use by ingest-ui in distinguishing those that can be submitted datasets, and an alt-names list to support deprecating assay names in favor of updated names.  assay_types.yaml gets a schema.

### CODE REVIEW

**Review by cborromeo — APPROVED** [review]
I think these changes look fine.

**Comment by yuanzhou** [comment]
I'll take care of the deploy on DEV once all other reviewers approve this.

**Review by ngehlenborg — COMMENTED** [review]
Looks ok to me for now but we will ultimately need to find another system to treat assays as first class entities (this API might be the first step in that direction) and to handle derived datasets better (for example, this approach, with API or without, will quickly break down once we have different versions of pipelines rolled out).

**Comment by yuanzhou** [comment]
@jswelling what is the status of this PR? Are we supposed to merge it and deploy on DEV for testing?

**Comment by jswelling** [comment]
@yuanzhou yes, I'd like to get it merged and deployed to test.  Sorry, missed your msg earlier.

**Comment by yuanzhou** [comment]
I'll be merging this PR shortly and deploy on DEV for testing with a reindex as well.

**Pull request merged**
