### PR TITLE
Mccalluc/check has visualization

### PR DESCRIPTION
**Pull request by mccalluc**
Towards:
- https://github.com/hubmapconsortium/portal-visualization/issues/37
- https://github.com/hubmapconsortium/portal-ui/issues/2509

@yuanzhou : The [last four commits](https://github.com/hubmapconsortium/search-api/commits/test-release) have had failing tests. I think we've agreed that each developer is responsible for making sure that tests pass before merging, so I'm not sure why this happened.

Filing this as draft until tests pass on the base, and then those fixes can be merged into this branch.

### CODE REVIEW

**Comment by yuanzhou** [comment]
@mccalluc I noticed the CI failed and I believe it was not due to the code changes made in this repo. Something with Travis. I'll look into it. We needed those new changes for testing and were pretty confident about the failed test not due to those changes so went ahead.

**Comment by yuanzhou** [comment]
@mccalluc not sure why but using the default python version fixed the Travis CI build: https://github.com/hubmapconsortium/search-api/commit/08fbc1c737df17309efe90774c310235d8254b61 FYI, we are also running Python v3.6 on all the deployment VMs.

**Comment by mccalluc** [comment]
@yuanzhou -- Thank you for addressing the original failure, but I see that with the [latest commit](https://github.com/hubmapconsortium/search-api/commit/0a433f78e4cdd16a66f9689d67f828373b072b97) tests are failing on the default branch again. Please make PRs, and please do not merge PRs until tests pass.

**Comment by yuanzhou** [comment]
Sorry @mccalluc for the confusion. I did a revert PR earlier then deleted that branch after seeing the Travis CI build passed. This branch deletion caused another build to fail during the PR check due to missing that branch. 

I restored that revert branch and bumped the version for the next round of release, Travis CI build passed this time.

**Review by jswelling — APPROVED** [review]
This is outside the range of code I'm familiar with.

**Comment by yuanzhou** [comment]
@mccalluc is this draft PR still relevant? We've upgraded to Python 3.9 and started using `main` as the default branch too.

**Comment by yuanzhou** [comment]
No longer use `test-release` branch.

**Comment by mccalluc** [comment]
@yuanzhou -- This is ready for review / merge.

**Review by yuanzhou — APPROVED** [review]

**Comment by yuanzhou** [comment]
FYI, I've merged this PR to `main` but haven't deployed on TEST nor released to PROD. Waiting on other changes for a PROD release, probably after the HuBMAP meeting.

**Pull request merged**
