### PR TITLE
John conroy/yaml deps

### LINKED ISSUE #745: Completely refactor out schema yamls from portal translation
As part of the deprecation effort to favor the new soft assay migration and also based on previous conversation: https://github.com/hubmapconsortium/search-api/pull/731

### Items to be addressed:
- We are not using `src/search-schema/data/definitions/fields.yaml`, the portal team may still double check if portal translation relies on it for any handlings. We should refactor this out since it'll be a maintenance debt as the properties change or new ones being added.

- `organ_types.yaml` is still being consumed by the portal code. Move to one of the UBKG calls: 

    * `GET https://ontology-api.dev.hubmapconsortium.org/organs?application_context=HUBMAP` 
    * `GET https://ontology-api.dev.hubmapconsortium.org/organs/by-code?application_context=HUBMAP`

- `tissue_sample_types.yaml` is not needed, and there's no equivalent UBKG call, need to be refactored out from portal code.

- `data_access_levels.yaml` and `dataset_status_types.yaml` are still tied to the portal translation code, we should add a new module inside portal directory with all the yaml value converted to constants to cater future updates.

### Items have already been addressed or no longer relavant:
- `assay_types.yaml` had been refactored out as part of the initial soft assay release.

- `entity_types.yaml` is no longer being used.

@john-conroy you'll need to handle the transition in portal code and once all gets tested and verified, I'll obsolete them from the codebase.

### PR DESCRIPTION
**Pull request by john-conroy**
Fix #745.

### CODE REVIEW

**Review by lchoy — APPROVED** [review]

**Comment by john-conroy** [comment]
@yuanzhou Looks ready to put this on DEV.

**Comment by yuanzhou** [comment]
@john-conroy thanks for the effort! Do you think we can also remove the yaml files at https://github.com/hubmapconsortium/search-api/tree/john-conroy/yaml-deps/src/search-schema as part of this PR?

**Comment by john-conroy** [comment]
@yuanzhou there are still references to the search-schema yaml files in `src/libs/assay_type.py`.

**Comment by AlanSimmons** [comment]
@john-conroy Is there anything in particular that I should be reviewing?

**Comment by yuanzhou** [comment]
> @yuanzhou there are still references to the search-schema yaml files in `src/libs/assay_type.py`. I've deleted the yaml addressed in this PR.

Thanks, @john-conroy. I'll take care of that `src/libs/assay_type.py` and the related pieces afterwards.

**Comment by john-conroy** [comment]
@AlanSimmons you were automatically tagged as reviewer because you were a code owner of the deleted yaml files.

**Review by AlanSimmons — APPROVED** [review]

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
