### PR TITLE
Add MIBI and mibi_deepcell

### PR DESCRIPTION
**Pull request by jswelling**
Adds a definition for Multiplex Ion Beam Imaging to assay_types, plus mibi_deepcell, a derived assay.

### CODE REVIEW

**Review by cebriggs7135 — COMMENTED** [review]
the alternate mibi names should include the upper case “MIBI”.

**Comment by jswelling** [comment]
The string MIBI (in uppercase) should be covered by the "main name", which is the string at the top of the YAML block.

**Review by cebriggs7135 — APPROVED** [review]

**Review by yuanzhou — APPROVED** [review]

**Comment by yuanzhou** [comment]
@jswelling can you please sync the new changes from test-release branch into your branch to fix the Travis build error? Your changes didn’t cause the build error.

**Comment by jswelling** [comment]
@yuanzhou I merged the HEAD of test-release, but the tests are still failing.

**Review by icaoberg — APPROVED** [review]

**Comment by yuanzhou** [comment]
@jswelling the error from the Travis CI build is different from what I had addressed. It looks like the portal transformation complained: https://app.travis-ci.com/github/hubmapconsortium/search-api/builds/245458219

**Comment by jswelling** [comment]
@yuanzhou the new problem was caused by tabs masquerading as spaces in a yaml file- I've fixed it, and the tests passed.

**Pull request merged**
