### PR TITLE
Mccalluc/imc3d

### PR DESCRIPTION
**Pull request by mccalluc**
at https://github.com/hubmapconsortium/ingest-validation-tools/pull/592#pullrequestreview-601238327 Joel wrote:
> The new type will need to be added to https://github.com/hubmapconsortium/search-api/blob/master/src/search-schema/data/definitions/enums/assay_types.yaml . I'm not clear on how you're supposed to create a branch and a PR to integrate with Bill's current deployment process.

@shirey : Is this the correct branch to make a PR against? Anything else wrong?

@pecan88 : Does the process described work, or would you prefer something different? Does it make sense to flag both you and Elizabeth, or is Elizabeth really the primary owner? (The google doc isn't connecting to you or Elizabeth when I try `@`... perhaps give the exact username here which should be asked for review?)

(I see the travis error, so let me fix that...)

### CODE REVIEW

**Review by shirey — APPROVED** [review]
Looks fine.  I won't merge until it is ready @yuanzhou after approved by all please get it out on TEST.

**Review by yuanzhou — APPROVED** [review]
I'll redeploy on TEST and reindex upon the approvals from all requested reviewers.

**Comment by pecan88** [comment]
@computationdoc - would you please review this PR for approval / issues?  The reason I'm looping you in is based on a conversation with Chuck and our seeking to know how best to support HuBMAP ontology efforts wrt assay naming and/or hierarchy of association (e.g. Imaging Mass Spectrometry is parent of DESI, MALDI+, MALDI-, MALDI-FTICR, nanoDESI, GCIB-SIMSPhIMS)

**Comment by mccalluc** [comment]
@pecan88 : On slack, Jonathan says:
> On the PR, I talked with Peter and he will resolve the hierarchy of IMC with Jeff Spraggins

So I'm waiting for your review.

**Review by jswelling — APPROVED** [review]
Yup, that's what's needed.

**Comment by pecan88** [comment]
I am deprecating the HuBMAP Assay List Google document and making the Portal the source of truth for assay names & organization.  Direct folks asking for a list of assays to help@hubmapconsortium.org.

Re: the Mass Spec assays, @JAH386 will work with Jeff Spraggins and team of Vanderbilt to verify and adjust the Mass Spec assay organization as needed.  We'll post an update no later than EOD March 10th.

**Comment by pecan88** [comment]
I am approving making the Assay_Types YAML the source of truth for assays (or at least until a PI contradicts me).

**Review by pecan88 — APPROVED** [review]

**Pull request merged**
