### PR TITLE
Add OpenSearch scroll search support

### PR DESCRIPTION
**Pull request by kburke**
Add /<index>/scroll-search endpoint, and methods to support opening, reading, and closing based on request attributes.

### CODE REVIEW

**Comment by maxsibilla** [comment]
@kburke are the only files being updated located in the [search-adaptor](https://github.com/dbmi-pitt/search-adaptor) submodule? If so then you should create a branch off of `main` in that repo and then initiate a PR there. Once that is merged you can create a PR in this repo that bumps the commit of the submodule

**Comment by kburke** [comment]
>

**Comment by kburke** [comment]
@maxsibilla When I look at https://github.com/dbmi-pitt/search-adaptor/compare/main...karlburke/files-api and it shows it is 2 commits ahead of main, can I just create a PR there, without additional branching, committing, etc?  Do I also need to close this PR, which warns me there are unmerged commits?

**Comment by maxsibilla** [comment]
@kburke Well merge it into dev-integrate first. Once that is approved then you can create a new PR here that simply bumps the commit version of the submodule. If you look at `search-adaptor` [here](https://github.com/hubmapconsortium/search-api/tree/dev-integrate/src) you can see the commit that it is currently referencing

**Review by yuanzhou — CHANGES_REQUESTED** [review]
@kburke you'll need to point to the search-adaptor dev-integrate branch for the testing once it's merged there first. https://github.com/hubmapconsortium/search-api/blob/karlburke/files-api/.gitmodules#L4

**Comment by yuanzhou** [comment]
I've updated the reference to the latest submodule `dev-integrate` branch (has the scroll-search merged), will merge and redeploy on DEV. The corresponding changes from files-api are not in place yet.

**Comment by yuanzhou** [comment]
We won't need a new PR in this repo when we merge the submodule into `main` for release.

**Pull request merged**
